/* translate grani in /Users/jimbevington/code/nannav2/jb-Nanna-Grani.fasl to C
 *   written Tue 17-Apr-18 at 20:16 by CLM of 21-Mar-12
 */

#include <mus-config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <math.h>
#include <signal.h>
#include <cmus.h>

static sig_atomic_t got_sigint = 0; /* catch C-C if hung */
static void sig_err(int sig) {got_sigint = sig;}

int clm_grani (double *clm_double, int datar_len, int *clm_int, int datai_len)
{
  /* The _clm_* variables are temporary values generated by the run macro */
  void (*old_SIGINT)(int);
  mus_long_t LOOP_LIMIT_355, _clm_359, LOOP_LIMIT_323, _clm_328, _clm_327, _clm_289, _clm_256, _clm_239, _clm_219, _clm_188, _clm_163;
  bool _clm_505, _clm_498, _clm_491, _clm_484, _clm_479, _clm_472, _clm_465, _clm_459, _clm_452, _clm_445, _clm_438, _clm_432, _clm_420, _clm_415, _clm_395, _clm_382, _clm_367, _clm_353, _clm_343, _clm_336, _clm_317, _clm_315, _clm_313, _clm_311, _clm_298, _clm_282, _clm_269, _clm_261, _clm_248, _clm_228, _clm_208, _clm_207, G196, _clm_198, _clm_197, _clm_155;
  double _clm_493, _clm_492, _clm_486, _clm_485, _clm_474, _clm_473, _clm_467, _clm_466, _clm_461, _clm_460, _clm_454, _clm_453, _clm_447, _clm_446, _clm_440, _clm_439, _clm_428, _clm_427, _clm_426, FRAC, _clm_424, _clm_423, _clm_422, _clm_406, _clm_405, _clm_404, _clm_403, _clm_402, _clm_401, _clm_400, _clm_399, _clm_398, _clm_397, _clm_396, _clm_390, _clm_389, _clm_388, _clm_387, _clm_386, _clm_385, _clm_384, _clm_383, _clm_377, _clm_376, _clm_372, _clm_348, _clm_346, C, _clm_318, _clm_304, _clm_303, _clm_302, _clm_301, _clm_300, _clm_299, _clm_293, _clm_292, _clm_291, _clm_290, _clm_288, _clm_287, _clm_286, _clm_285, _clm_284, _clm_283, _clm_277, _clm_276, _clm_275, _clm_274, _clm_273, _clm_272, _clm_271, _clm_270, _clm_264, _clm_263, _clm_262, _clm_254, _clm_253, _clm_252, _clm_251, _clm_250, _clm_249, _clm_243, _clm_242, _clm_241, _clm_237, _clm_236, _clm_235, _clm_234, _clm_233, _clm_232, _clm_231, _clm_230, _clm_229, _clm_223, _clm_222, _clm_221, _clm_214, _clm_190, _clm_189, _clm_177, _clm_176, _clm_175, _clm_174, _clm_173, _clm_172, _clm_170, _clm_169, _clm_165, _clm_162, _clm_161;
  mus_any *GR_DEGREE_SPREAD = NULL, *GR_DEGREE = NULL, *GR_DIST_SPREAD = NULL, *GR_DIST = NULL, *_OUTPUT_ = NULL, *GR_DENS_SPREAD_ENV = NULL, *GR_DENS_ENV = NULL, *GR_START_SPREAD = NULL, *GR_START = NULL, *SR_SPREAD_ENV = NULL, *SR_ENV = NULL, *GR_DUR_SPREAD = NULL, *GR_DUR = NULL, *IN_FILE_READER = NULL, *AMP_ENV = NULL, *GR_ENV_END = NULL, *GR_ENV = NULL, *LOC = NULL, *GR_INT_ENV = NULL;
  void *all_gens = NULL;
  mus_long_t clm_beg, clm_end;
  
  all_gens = clm_make_genbag();
  clm_beg = clm_to_mus_long_t(clm_int, 1);
  clm_end = clm_to_mus_long_t(clm_int, 3);
  #define GR_OFFSET 5
  #define GR_OFFSET_r 0
  #define GR_SAMPLES 7
  #define GR_SAMPLES_r 1
  #define INTERP_GR_ENVS 9
  #define INTERP_GR_ENVS_r 2
  if (CLM_ENV_P(11))
    GR_INT_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(11) + 3), /* breakpoints */
        clm_int[CLM_ILOC(11) + 2], /* num points */
        clm_double[CLM_RLOC(11) + 1], /* scaler */
        clm_double[CLM_RLOC(11) + 2], /* offset */
        clm_double[CLM_RLOC(11)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(11) + 3], /* end */
        NULL)); /* original data -- handled internally */
  #define GR_WHERE 13
  #define GR_WHERE_r 4
  if (CLM_LOCSIG_P(15))
    LOC = clm_add_gen_to_genbag(all_gens, 
      mus_make_locsig(
        clm_double[CLM_RLOC(15)],
        clm_double[CLM_RLOC(15) + 1],
        clm_double[CLM_RLOC(15) + 2],
        clm_int[CLM_ILOC(15) + 2],
        clm_output(), (clm_reverb()) ? mus_channels(clm_reverb()) : 0, clm_reverb(),
        clm_int[CLM_ILOC(15) + 3]));
  #define _clm_164 17
  #define _clm_164_r 6
  #define GR_START_SAMPLE 19
  #define GR_START_SAMPLE_r 7
  #define _clm_166 21
  #define _clm_166_r 8
  #define _clm_171 23
  #define _clm_171_r 9
  if (CLM_TABLE_LOOKUP_P(25))
    GR_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_table_lookup(
        clm_double[CLM_RLOC(25)],
        clm_double[CLM_RLOC(25) + 1],
        (double *)(clm_double + CLM_RLOC(25) + 2),
        clm_int[CLM_ILOC(25) + 2],/* size */
        clm_int[CLM_ILOC(25) + 3])); /* type */
  if (CLM_TABLE_LOOKUP_P(27))
    GR_ENV_END = clm_add_gen_to_genbag(all_gens, 
      mus_make_table_lookup(
        clm_double[CLM_RLOC(27)],
        clm_double[CLM_RLOC(27) + 1],
        (double *)(clm_double + CLM_RLOC(27) + 2),
        clm_int[CLM_ILOC(27) + 2],/* size */
        clm_int[CLM_ILOC(27) + 3])); /* type */
  if (CLM_ENV_P(29))
    AMP_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(29) + 3), /* breakpoints */
        clm_int[CLM_ILOC(29) + 2], /* num points */
        clm_double[CLM_RLOC(29) + 1], /* scaler */
        clm_double[CLM_RLOC(29) + 2], /* offset */
        clm_double[CLM_RLOC(29)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(29) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_SRC_P(31))
    {
      if (clm_int[CLM_ILOC(31) + 3])
        {
          mus_any *rd = NULL;
          rd = clm_add_gen_to_genbag(all_gens, 
            mus_make_readin(
              (char *)(clm_int + CLM_ILOC(31) + 7 + 2), /* filename */
                clm_int[CLM_ILOC(31) + 4], /* chan */
                clm_to_mus_long_t(clm_int, CLM_ILOC(31) + 5), /* start */
                1)); /* direction */
          IN_FILE_READER = clm_add_gen_to_genbag(all_gens, 
            clm_make_src(clm_as_needed_input,
              clm_double[CLM_RLOC(31)], /* srate */
              clm_int[CLM_ILOC(31) + 2], /* width */
              (void *)rd));
         }
    }
  #define FIRST_GRAIN 33
  #define FIRST_GRAIN_r 14
  #define BEG 35
  #define BEG_r 15
  #define _clm_186 37
  #define _clm_186_r 16
  #define _clm_191 39
  #define _clm_191_r 17
  #define GR_DENS 41
  #define GR_DENS_r 18
  #define GR_DENS_SPREAD 43
  #define GR_DENS_SPREAD_r 19
  #define _SRATE_ 45
  #define _SRATE__r 20
  #define END 47
  #define END_r 21
  #define _clm_199 49
  #define _clm_199_r 22
  #define _clm_204 51
  #define _clm_204_r 23
  #define GRAINS 53
  #define GRAINS_r 24
  #define GRAIN_COUNTER 55
  #define GRAIN_COUNTER_r 25
  #define VERBOSE 57
  #define VERBOSE_r 26
  #define SAMPLES 59
  #define SAMPLES_r 27
  #define _clm_215 61
  #define _clm_215_r 28
  #define _clm_220 63
  #define _clm_220_r 29
  #define GR_FROM_BEG 65
  #define GR_FROM_BEG_r 30
  if (CLM_ENV_P(67))
    GR_DUR = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(67) + 3), /* breakpoints */
        clm_int[CLM_ILOC(67) + 2], /* num points */
        clm_double[CLM_RLOC(67) + 1], /* scaler */
        clm_double[CLM_RLOC(67) + 2], /* offset */
        clm_double[CLM_RLOC(67)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(67) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(69))
    GR_DUR_SPREAD = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(69) + 3), /* breakpoints */
        clm_int[CLM_ILOC(69) + 2], /* num points */
        clm_double[CLM_RLOC(69) + 1], /* scaler */
        clm_double[CLM_RLOC(69) + 2], /* offset */
        clm_double[CLM_RLOC(69)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(69) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(71))
    SR_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(71) + 3), /* breakpoints */
        clm_int[CLM_ILOC(71) + 2], /* num points */
        clm_double[CLM_RLOC(71) + 1], /* scaler */
        clm_double[CLM_RLOC(71) + 2], /* offset */
        clm_double[CLM_RLOC(71)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(71) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(73))
    SR_SPREAD_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(73) + 3), /* breakpoints */
        clm_int[CLM_ILOC(73) + 2], /* num points */
        clm_double[CLM_RLOC(73) + 1], /* scaler */
        clm_double[CLM_RLOC(73) + 2], /* offset */
        clm_double[CLM_RLOC(73)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(73) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(75))
    GR_START = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(75) + 3), /* breakpoints */
        clm_int[CLM_ILOC(75) + 2], /* num points */
        clm_double[CLM_RLOC(75) + 1], /* scaler */
        clm_double[CLM_RLOC(75) + 2], /* offset */
        clm_double[CLM_RLOC(75)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(75) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(77))
    GR_START_SPREAD = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(77) + 3), /* breakpoints */
        clm_int[CLM_ILOC(77) + 2], /* num points */
        clm_double[CLM_RLOC(77) + 1], /* scaler */
        clm_double[CLM_RLOC(77) + 2], /* offset */
        clm_double[CLM_RLOC(77)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(77) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(79))
    GR_DENS_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(79) + 3), /* breakpoints */
        clm_int[CLM_ILOC(79) + 2], /* num points */
        clm_double[CLM_RLOC(79) + 1], /* scaler */
        clm_double[CLM_RLOC(79) + 2], /* offset */
        clm_double[CLM_RLOC(79)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(79) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(81))
    GR_DENS_SPREAD_ENV = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(81) + 3), /* breakpoints */
        clm_int[CLM_ILOC(81) + 2], /* num points */
        clm_double[CLM_RLOC(81) + 1], /* scaler */
        clm_double[CLM_RLOC(81) + 2], /* offset */
        clm_double[CLM_RLOC(81)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(81) + 3], /* end */
        NULL)); /* original data -- handled internally */
  #define GR_START_SCALER 83
  #define GR_START_SCALER_r 39
  #define _clm_225 85
  #define _clm_225_r 40
  #define IN_START_VALUE 87
  #define IN_START_VALUE_r 41
  #define _clm_240 89
  #define _clm_240_r 42
  #define IN_FILE_SR 91
  #define IN_FILE_SR_r 43
  #define IN_START 93
  #define IN_START_r 44
  #define GRAIN_DURATION_LIMIT 95
  #define GRAIN_DURATION_LIMIT_r 45
  #define _clm_245 97
  #define _clm_245_r 46
  #define GR_DURATION 99
  #define GR_DURATION_r 47
  #define _clm_257 101
  #define _clm_257_r 48
  #define _clm_258 103
  #define _clm_258_r 49
  #define SR_LINEAR 105
  #define SR_LINEAR_r 50
  #define SRATE_BASE 107
  #define SRATE_BASE_r 51
  #define _clm_266 109
  #define _clm_266_r 52
  #define _clm_279 111
  #define _clm_279_r 53
  #define GR_SRATE 113
  #define GR_SRATE_r 54
  #define SRATE_RATIO 115
  #define SRATE_RATIO_r 55
  #define IN_SAMPLES 117
  #define IN_SAMPLES_r 56
  #define _clm_295 119
  #define _clm_295_r 57
  #define _clm_305 121
  #define _clm_305_r 58
  #define _clm_306 123
  #define _clm_306_r 59
  #define _clm_308 125
  #define _clm_308_r 60
  #define WHERE_TO 127
  #define WHERE_TO_r 61
  #define WHERE 129
  #define WHERE_r 62
  C = clm_double[100];
  #define BINS 131
  #define BINS_r 63
  #define _clm_340 133
  #define _clm_340_r 64
  #define _clm_344 135
  #define _clm_344_r 65
  #define _clm_345 137
  #define _clm_345_r 66
  _OUTPUT_ = clm_output();
  if (CLM_ENV_P(141))
    GR_DIST = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(141) + 3), /* breakpoints */
        clm_int[CLM_ILOC(141) + 2], /* num points */
        clm_double[CLM_RLOC(141) + 1], /* scaler */
        clm_double[CLM_RLOC(141) + 2], /* offset */
        clm_double[CLM_RLOC(141)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(141) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(143))
    GR_DIST_SPREAD = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(143) + 3), /* breakpoints */
        clm_int[CLM_ILOC(143) + 2], /* num points */
        clm_double[CLM_RLOC(143) + 1], /* scaler */
        clm_double[CLM_RLOC(143) + 2], /* offset */
        clm_double[CLM_RLOC(143)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(143) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(145))
    GR_DEGREE = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(145) + 3), /* breakpoints */
        clm_int[CLM_ILOC(145) + 2], /* num points */
        clm_double[CLM_RLOC(145) + 1], /* scaler */
        clm_double[CLM_RLOC(145) + 2], /* offset */
        clm_double[CLM_RLOC(145)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(145) + 3], /* end */
        NULL)); /* original data -- handled internally */
  if (CLM_ENV_P(147))
    GR_DEGREE_SPREAD = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(147) + 3), /* breakpoints */
        clm_int[CLM_ILOC(147) + 2], /* num points */
        clm_double[CLM_RLOC(147) + 1], /* scaler */
        clm_double[CLM_RLOC(147) + 2], /* offset */
        clm_double[CLM_RLOC(147)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(147) + 3], /* end */
        NULL)); /* original data -- handled internally */
  #define _clm_379 149
  #define _clm_379_r 72
  #define DEG 151
  #define DEG_r 73
  #define _clm_392 153
  #define _clm_392_r 74
  #define DIST 155
  #define DIST_r 75
  #define DIST_SCL 157
  #define DIST_SCL_r 76
  #define DIST_RSCL 159
  #define DIST_RSCL_r 77
  #define _REVERB_ 161
  #define _REVERB__r 78
  #define _clm_411 163
  #define _clm_411_r 79
  #define REVERB_AMOUNT 165
  #define REVERB_AMOUNT_r 80
  #define OUT_CHANS 167
  #define OUT_CHANS_r 81
  #define _clm_435 169
  #define _clm_435_r 82
  #define _clm_441 171
  #define _clm_441_r 83
  #define _clm_442 173
  #define _clm_442_r 84
  #define _clm_448 175
  #define _clm_448_r 85
  #define _clm_449 177
  #define _clm_449_r 86
  #define _clm_455 179
  #define _clm_455_r 87
  #define _clm_456 181
  #define _clm_456_r 88
  #define _clm_462 183
  #define _clm_462_r 89
  #define _clm_468 185
  #define _clm_468_r 90
  #define _clm_469 187
  #define _clm_469_r 91
  #define _clm_475 189
  #define _clm_475_r 92
  #define _clm_481 191
  #define _clm_481_r 93
  #define _clm_487 193
  #define _clm_487_r 94
  #define _clm_488 195
  #define _clm_488_r 95
  #define _clm_494 197
  #define _clm_494_r 96
  #define _clm_499 199
  #define _clm_499_r 97
  #define LAST_IN_SAMPLE 201
  #define LAST_IN_SAMPLE_r 98
  #define _clm_501 203
  #define _clm_501_r 99
  got_sigint = 0; old_SIGINT = clm_signal(SIGINT, sig_err);                     /* trap SIGINT */

SAMPLE_LOOP_BEGIN:
  if (got_sigint != 0) {clm_int[0] = (int)got_sigint; goto RUN_ALL_DONE;}
                                                                                /* (tagbody */
NEXT_LOOP_L_27:
                                                                                /* (if t */
  if (false) goto L_148;
  goto L_149;
L_148:
                                                                                /* (progn */
                                                                                /* (go end-loop */
  goto END_LOOP_L_27;
L_149:
                                                                                /* (if (< gr-offset gr-samples) */
  _clm_155 = (((clm_int[GR_OFFSET] == 2) ? clm_double[GR_OFFSET_r] : (double)(clm_int[GR_OFFSET + 1])) < ((clm_int[GR_SAMPLES] == 2) ? clm_double[GR_SAMPLES_r] : (double)(clm_int[GR_SAMPLES + 1]))); /* (< GR-OFFSET GR-SAMPLES) */
  if ((!_clm_155)) goto L_153;
                                                                                /* (progn */
                                                                                /* (if interp-gr-envs */
  if (((clm_int[INTERP_GR_ENVS] == 0) && (clm_int[INTERP_GR_ENVS + 1] == 0))) goto L_158;
  _clm_161 = mus_env(GR_INT_ENV);                                               /* (env GR-INT-ENV) */
  clm_int[GR_WHERE + 0] = 2;
  clm_double[GR_WHERE_r+0] = _clm_161;                                          /* (setf GR-WHERE _clm_161) */
  goto L_159;
L_158:
L_159:
                                                                                /* (+ gr-start-sample gr-offset) */
  if ((clm_int[GR_START_SAMPLE + 0] == 1) && (clm_int[GR_OFFSET + 0] == 1))
    {clm_int[_clm_164 + 0] = 1;
  clm_int[_clm_164 + 0 + 1] = ((clm_int[GR_START_SAMPLE + 0 + 1]) + (clm_int[GR_OFFSET + 0 + 1]));}
  else {clm_int[_clm_164 + 0] = 2;
  clm_double[_clm_164_r+0] = ((((clm_int[GR_START_SAMPLE] == 2) ? clm_double[GR_START_SAMPLE_r] : (double)(clm_int[GR_START_SAMPLE + 1]))) + (((clm_int[GR_OFFSET] == 2) ? clm_double[GR_OFFSET_r] : (double)(clm_int[GR_OFFSET + 1]))));}
  _clm_163 = (mus_long_t)floor((double)(((clm_int[_clm_164] == 2) ? clm_double[_clm_164_r] : (double)(clm_int[_clm_164 + 1])))); /* (floor _clm_164) */
                                                                                /* (if interp-gr-envs */
  if (((clm_int[INTERP_GR_ENVS] == 0) && (clm_int[INTERP_GR_ENVS + 1] == 0))) goto L_167;
                                                                                /* (- 1 gr-where) */
  if ((1) && (clm_int[GR_WHERE + 0] == 1))
    {clm_int[_clm_171 + 0] = 1;
  clm_int[_clm_171 + 0 + 1] = ((1) - (clm_int[GR_WHERE + 0 + 1]));}
  else {clm_int[_clm_171 + 0] = 2;
  clm_double[_clm_171_r+0] = ((1) - (((clm_int[GR_WHERE] == 2) ? clm_double[GR_WHERE_r] : (double)(clm_int[GR_WHERE + 1]))));}
  _clm_172 = mus_table_lookup_unmodulated(GR_ENV);
                                                                                /* (* _clm_171 _clm_172) */
  _clm_170 = ((((clm_int[_clm_171] == 2) ? clm_double[_clm_171_r] : (double)(clm_int[_clm_171 + 1]))) * (_clm_172));
  _clm_174 = mus_table_lookup_unmodulated(GR_ENV_END);
                                                                                /* (* gr-where _clm_174) */
  _clm_173 = ((((clm_int[GR_WHERE] == 2) ? clm_double[GR_WHERE_r] : (double)(clm_int[GR_WHERE + 1]))) * (_clm_174));
                                                                                /* (+ _clm_170 _clm_173) */
  _clm_169 = ((_clm_170) + (_clm_173));
  clm_int[_clm_166 + 0] = 2;
  clm_double[_clm_166_r+0] = _clm_169;                                          /* (setf _clm_166 _clm_169) */
  goto L_168;
L_167:
  _clm_175 = mus_table_lookup_unmodulated(GR_ENV);
  clm_int[_clm_166 + 0] = 2;
  clm_double[_clm_166_r+0] = _clm_175;                                          /* (setf _clm_166 _clm_175) */
L_168:
  _clm_176 = mus_env(AMP_ENV);                                                  /* (env AMP-ENV) */
  _clm_177 = mus_src(IN_FILE_READER, 0.0, NULL);
                                                                                /* (* _clm_166 _clm_176 _clm_177) */
  _clm_165 = ((((clm_int[_clm_166] == 2) ? clm_double[_clm_166_r] : (double)(clm_int[_clm_166 + 1]))) * (_clm_176) * (_clm_177));
  _clm_162 = clm_locsig(LOC, _clm_163, _clm_165);
  clm_int[GR_OFFSET + 0] = 1;
  clm_int[GR_OFFSET + 0 + 1] += 1;                                              /* (incf GR-OFFSET 1) */
  goto L_154;
L_153:
                                                                                /* (progn */
                                                                                /* (if first-grain */
  if (((clm_int[FIRST_GRAIN] == 0) && (clm_int[FIRST_GRAIN + 1] == 0))) goto L_181;
  clm_int[FIRST_GRAIN + 0] = 0;
  clm_int[FIRST_GRAIN + 0 + 1] = 0;                                             /* (setf FIRST-GRAIN NIL) */
  clm_int[GR_START_SAMPLE + 0] = clm_int[BEG + 0];
  clm_int[GR_START_SAMPLE + 0 + 1] = clm_int[BEG + 0 + 1];
  clm_double[GR_START_SAMPLE_r + 0] = clm_double[BEG_r + 0];                    /* (setf GR-START-SAMPLE BEG) */
  goto L_182;
L_181:
                                                                                /* (progn */
                                                                                /* (+ gr-dens gr-dens-spread) */
  if ((clm_int[GR_DENS + 0] == 1) && (clm_int[GR_DENS_SPREAD + 0] == 1))
    {clm_int[_clm_191 + 0] = 1;
  clm_int[_clm_191 + 0 + 1] = ((clm_int[GR_DENS + 0 + 1]) + (clm_int[GR_DENS_SPREAD + 0 + 1]));}
  else {clm_int[_clm_191 + 0] = 2;
  clm_double[_clm_191_r+0] = ((((clm_int[GR_DENS] == 2) ? clm_double[GR_DENS_r] : (double)(clm_int[GR_DENS + 1]))) + (((clm_int[GR_DENS_SPREAD] == 2) ? clm_double[GR_DENS_SPREAD_r] : (double)(clm_int[GR_DENS_SPREAD + 1]))));}
  _clm_190 = (1.0 / (double)((clm_int[_clm_191] == 2) ? clm_double[_clm_191_r] : (double)(clm_int[_clm_191 + 1]))); /* (/ _clm_191) */
                                                                                /* (* _clm_190 *srate*) */
  _clm_189 = ((_clm_190) * (((clm_int[_SRATE_] == 2) ? clm_double[_SRATE__r] : (double)(clm_int[_SRATE_ + 1]))));
  _clm_188 = (mus_long_t)floor((double)(_clm_189));                             /* (floor _clm_189) */
                                                                                /* (+ gr-start-sample _clm_188) */
  if ((clm_int[GR_START_SAMPLE + 0] == 1) && (1))
    {clm_int[_clm_186 + 0] = 1;
  clm_int[_clm_186 + 0 + 1] = ((clm_int[GR_START_SAMPLE + 0 + 1]) + (_clm_188));}
  else {clm_int[_clm_186 + 0] = 2;
  clm_double[_clm_186_r+0] = ((((clm_int[GR_START_SAMPLE] == 2) ? clm_double[GR_START_SAMPLE_r] : (double)(clm_int[GR_START_SAMPLE + 1]))) + (_clm_188));}
  clm_int[GR_START_SAMPLE + 0] = clm_int[_clm_186 + 0];
  clm_int[GR_START_SAMPLE + 0 + 1] = clm_int[_clm_186 + 0 + 1];
  clm_double[GR_START_SAMPLE_r + 0] = clm_double[_clm_186_r + 0];               /* (setf GR-START-SAMPLE _clm_186) */
                                                                                /* (if (or (> gr-start-sample end)
     (if (/= grains 0)
         (>= grain-counter grains)
         nil)) */
  _clm_198 = (((clm_int[GR_START_SAMPLE] == 2) ? clm_double[GR_START_SAMPLE_r] : (double)(clm_int[GR_START_SAMPLE + 1])) > ((clm_int[END] == 2) ? clm_double[END_r] : (double)(clm_int[END + 1]))); /* (> GR-START-SAMPLE END) */
  G196 = _clm_198;                                                              /* (setf G196 _clm_198) */
                                                                                /* (if g196 */
  if ((!G196)) goto L_200;
  clm_int[_clm_199 + 0] = 0;
  clm_int[_clm_199 + 0 + 1] = G196;                                             /* (setf _clm_199 G196) */
  goto L_201;
L_200:
                                                                                /* (if (/= grains 0) */
  _clm_207 = (((clm_int[GRAINS] == 2) ? clm_double[GRAINS_r] : (double)(clm_int[GRAINS + 1])) != 0); /* (neq GRAINS 0) */
  if ((!_clm_207)) goto L_205;
  _clm_208 = (((clm_int[GRAIN_COUNTER] == 2) ? clm_double[GRAIN_COUNTER_r] : (double)(clm_int[GRAIN_COUNTER + 1])) >= ((clm_int[GRAINS] == 2) ? clm_double[GRAINS_r] : (double)(clm_int[GRAINS + 1]))); /* (>= GRAIN-COUNTER GRAINS) */
  clm_int[_clm_204 + 0] = 0;
  clm_int[_clm_204 + 0 + 1] = _clm_208;                                         /* (setf _clm_204 _clm_208) */
  goto L_206;
L_205:
  clm_int[_clm_204 + 0] = 0;
  clm_int[_clm_204 + 0 + 1] = 0;                                                /* (setf _clm_204 NIL) */
L_206:
  clm_int[_clm_199 + 0] = clm_int[_clm_204 + 0];
  clm_int[_clm_199 + 0 + 1] = clm_int[_clm_204 + 0 + 1];
  clm_double[_clm_199_r + 0] = clm_double[_clm_204_r + 0];                      /* (setf _clm_199 _clm_204) */
L_201:
  _clm_197 = ((clm_int[_clm_199] == 2) ? clm_double[_clm_199_r] : (double)(clm_int[_clm_199 + 1])); /* (setf _clm_197 _clm_199) */
  if ((!_clm_197)) goto L_193;
                                                                                /* (progn */
                                                                                /* (if verbose */
  if (((clm_int[VERBOSE] == 0) && (clm_int[VERBOSE + 1] == 0))) goto L_211;
                                                                                /* (- end beg) */
  if ((clm_int[END + 0] == 1) && (clm_int[BEG + 0] == 1))
    {clm_int[_clm_215 + 0] = 1;
  clm_int[_clm_215 + 0 + 1] = ((clm_int[END + 0 + 1]) - (clm_int[BEG + 0 + 1]));}
  else {clm_int[_clm_215 + 0] = 2;
  clm_double[_clm_215_r+0] = ((((clm_int[END] == 2) ? clm_double[END_r] : (double)(clm_int[END + 1]))) - (((clm_int[BEG] == 2) ? clm_double[BEG_r] : (double)(clm_int[BEG + 1]))));}
  _clm_214 = ((double)((clm_int[SAMPLES] == 2) ? clm_double[SAMPLES_r] : (double)(clm_int[SAMPLES + 1])) / (double)((((clm_int[_clm_215] == 2) ? clm_double[_clm_215_r] : (double)(clm_int[_clm_215 + 1])))));
                                                                                /* (/ SAMPLES _clm_215) */
                                                                                /* (clm-print "; grains: ~d, sample ratio: ~f~%"  GRAIN-COUNTER _clm_214) */
  mus_error(0, "; grains: %lld, sample ratio: %f\n",
        (mus_long_t)((clm_int[GRAIN_COUNTER] == 2) ? clm_double[GRAIN_COUNTER_r] : (double)(clm_int[GRAIN_COUNTER + 1])),
        (double)_clm_214);
  goto L_212;
L_211:
L_212:
                                                                                /* (go end-loop */
  goto END_LOOP_L_27;
  goto L_194;
L_193:
L_194:
L_182:
  clm_int[GR_OFFSET + 0] = 1;
  clm_int[GR_OFFSET + 0 + 1] = 0;                                               /* (setf GR-OFFSET 0) */
                                                                                /* (- gr-start-sample beg) */
  if ((clm_int[GR_START_SAMPLE + 0] == 1) && (clm_int[BEG + 0] == 1))
    {clm_int[_clm_220 + 0] = 1;
  clm_int[_clm_220 + 0 + 1] = ((clm_int[GR_START_SAMPLE + 0 + 1]) - (clm_int[BEG + 0 + 1]));}
  else {clm_int[_clm_220 + 0] = 2;
  clm_double[_clm_220_r+0] = ((((clm_int[GR_START_SAMPLE] == 2) ? clm_double[GR_START_SAMPLE_r] : (double)(clm_int[GR_START_SAMPLE + 1]))) - (((clm_int[BEG] == 2) ? clm_double[BEG_r] : (double)(clm_int[BEG + 1]))));}
  _clm_219 = (mus_long_t)floor((double)(((clm_int[_clm_220] == 2) ? clm_double[_clm_220_r] : (double)(clm_int[_clm_220 + 1])))); /* (floor _clm_220) */
  clm_int[GR_FROM_BEG + 0] = 1;
  clm_int[GR_FROM_BEG + 0 + 1] = _clm_219;                                      /* (setf GR-FROM-BEG _clm_219) */
  mus_set_location(AMP_ENV, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_DUR, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_DUR_SPREAD, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(SR_ENV, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(SR_SPREAD_ENV, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_START, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_START_SPREAD, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_DENS_ENV, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_DENS_SPREAD_ENV, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  _clm_223 = mus_env(GR_START);                                                 /* (env GR-START) */
                                                                                /* (* _clm_223 gr-start-scaler) */
  _clm_222 = ((_clm_223) * (((clm_int[GR_START_SCALER] == 2) ? clm_double[GR_START_SCALER_r] : (double)(clm_int[GR_START_SCALER + 1]))));
                                                                                /* (if (/= (* (env gr-start-spread) gr-start-scaler) 0) */
  _clm_230 = mus_env(GR_START_SPREAD);                                          /* (env GR-START-SPREAD) */
                                                                                /* (* _clm_230 gr-start-scaler) */
  _clm_229 = ((_clm_230) * (((clm_int[GR_START_SCALER] == 2) ? clm_double[GR_START_SCALER_r] : (double)(clm_int[GR_START_SCALER + 1]))));
  _clm_228 = (_clm_229 != 0);                                                   /* (neq _clm_229 0) */
  if ((!_clm_228)) goto L_226;
  _clm_234 = mus_env(GR_START_SPREAD);                                          /* (env GR-START-SPREAD) */
                                                                                /* (* _clm_234 gr-start-scaler) */
  _clm_233 = ((_clm_234) * (((clm_int[GR_START_SCALER] == 2) ? clm_double[GR_START_SCALER_r] : (double)(clm_int[GR_START_SCALER + 1]))));
                                                                                /* (random _clm_233) */
  _clm_232 = mus_frandom((double)(_clm_233));
  _clm_237 = mus_env(GR_START_SPREAD);                                          /* (env GR-START-SPREAD) */
                                                                                /* (* _clm_237 gr-start-scaler) */
  _clm_236 = ((_clm_237) * (((clm_int[GR_START_SCALER] == 2) ? clm_double[GR_START_SCALER_r] : (double)(clm_int[GR_START_SCALER + 1]))));
  _clm_235 = ((double)_clm_236 / (double)((2)));
                                                                                /* (/ _clm_236 2) */
                                                                                /* (- _clm_232 _clm_235) */
  _clm_231 = ((_clm_232) - (_clm_235));
  clm_int[_clm_225 + 0] = 2;
  clm_double[_clm_225_r+0] = _clm_231;                                          /* (setf _clm_225 _clm_231) */
  goto L_227;
L_226:
  clm_int[_clm_225 + 0] = 1;
  clm_int[_clm_225 + 0 + 1] = 0;                                                /* (setf _clm_225 0) */
L_227:
                                                                                /* (+ _clm_222 _clm_225) */
  _clm_221 = ((_clm_222) + (((clm_int[_clm_225] == 2) ? clm_double[_clm_225_r] : (double)(clm_int[_clm_225 + 1]))));
  clm_int[IN_START_VALUE + 0] = 2;
  clm_double[IN_START_VALUE_r+0] = _clm_221;                                    /* (setf IN-START-VALUE _clm_221) */
                                                                                /* (* in-start-value in-file-sr) */
  if ((clm_int[IN_START_VALUE + 0] == 1) && (clm_int[IN_FILE_SR + 0] == 1))
    {clm_int[_clm_240 + 0] = 1;
  clm_int[_clm_240 + 0 + 1] = ((clm_int[IN_START_VALUE + 0 + 1]) * (clm_int[IN_FILE_SR + 0 + 1]));}
  else {clm_int[_clm_240 + 0] = 2;
  clm_double[_clm_240_r+0] = ((((clm_int[IN_START_VALUE] == 2) ? clm_double[IN_START_VALUE_r] : (double)(clm_int[IN_START_VALUE + 1]))) * (((clm_int[IN_FILE_SR] == 2) ? clm_double[IN_FILE_SR_r] : (double)(clm_int[IN_FILE_SR + 1]))));}
  _clm_239 = (mus_long_t)floor((double)(((clm_int[_clm_240] == 2) ? clm_double[_clm_240_r] : (double)(clm_int[_clm_240 + 1])))); /* (floor _clm_240) */
  clm_int[IN_START + 0] = 1;
  clm_int[IN_START + 0 + 1] = _clm_239;                                         /* (setf IN-START _clm_239) */
  _clm_243 = mus_env(GR_DUR);                                                   /* (env GR-DUR) */
                                                                                /* (if (/= (env gr-dur-spread) 0) */
  _clm_249 = mus_env(GR_DUR_SPREAD);                                            /* (env GR-DUR-SPREAD) */
  _clm_248 = (_clm_249 != 0);                                                   /* (neq _clm_249 0) */
  if ((!_clm_248)) goto L_246;
  _clm_252 = mus_env(GR_DUR_SPREAD);                                            /* (env GR-DUR-SPREAD) */
                                                                                /* (random _clm_252) */
  _clm_251 = mus_frandom((double)(_clm_252));
  _clm_254 = mus_env(GR_DUR_SPREAD);                                            /* (env GR-DUR-SPREAD) */
  _clm_253 = ((double)_clm_254 / (double)((2)));
                                                                                /* (/ _clm_254 2) */
                                                                                /* (- _clm_251 _clm_253) */
  _clm_250 = ((_clm_251) - (_clm_253));
  clm_int[_clm_245 + 0] = 2;
  clm_double[_clm_245_r+0] = _clm_250;                                          /* (setf _clm_245 _clm_250) */
  goto L_247;
L_246:
  clm_int[_clm_245 + 0] = 1;
  clm_int[_clm_245 + 0 + 1] = 0;                                                /* (setf _clm_245 0) */
L_247:
                                                                                /* (+ _clm_243 _clm_245) */
  _clm_242 = ((_clm_243) + (((clm_int[_clm_245] == 2) ? clm_double[_clm_245_r] : (double)(clm_int[_clm_245 + 1]))));
  _clm_241 = ((((clm_int[GRAIN_DURATION_LIMIT] == 2) ? clm_double[GRAIN_DURATION_LIMIT_r] : (double)(clm_int[GRAIN_DURATION_LIMIT + 1])) > _clm_242) ? ((clm_int[GRAIN_DURATION_LIMIT] == 2) ? clm_double[GRAIN_DURATION_LIMIT_r] : (double)(clm_int[GRAIN_DURATION_LIMIT + 1])) : _clm_242); /* (max GRAIN-DURATION-LIMIT _clm_242) */
  clm_int[GR_DURATION + 0] = 2;
  clm_double[GR_DURATION_r+0] = _clm_241;                                       /* (setf GR-DURATION _clm_241) */
                                                                                /* (* gr-duration *srate*) */
  if ((clm_int[GR_DURATION + 0] == 1) && (clm_int[_SRATE_ + 0] == 1))
    {clm_int[_clm_257 + 0] = 1;
  clm_int[_clm_257 + 0 + 1] = ((clm_int[GR_DURATION + 0 + 1]) * (clm_int[_SRATE_ + 0 + 1]));}
  else {clm_int[_clm_257 + 0] = 2;
  clm_double[_clm_257_r+0] = ((((clm_int[GR_DURATION] == 2) ? clm_double[GR_DURATION_r] : (double)(clm_int[GR_DURATION + 1]))) * (((clm_int[_SRATE_] == 2) ? clm_double[_SRATE__r] : (double)(clm_int[_SRATE_ + 1]))));}
  _clm_256 = (mus_long_t)floor((double)(((clm_int[_clm_257] == 2) ? clm_double[_clm_257_r] : (double)(clm_int[_clm_257 + 1])))); /* (floor _clm_257) */
  clm_int[GR_SAMPLES + 0] = 1;
  clm_int[GR_SAMPLES + 0 + 1] = _clm_256;                                       /* (setf GR-SAMPLES _clm_256) */
                                                                                /* (if (= sr-linear 0) */
  _clm_261 = (((clm_int[SR_LINEAR] == 2) ? clm_double[SR_LINEAR_r] : (double)(clm_int[SR_LINEAR + 1])) == 0); /* (== SR-LINEAR 0) */
  if ((!_clm_261)) goto L_259;
  _clm_263 = mus_env(SR_ENV);                                                   /* (env SR-ENV) */
                                                                                /* (if (/= (env sr-spread-env) 0) */
  _clm_270 = mus_env(SR_SPREAD_ENV);                                            /* (env SR-SPREAD-ENV) */
  _clm_269 = (_clm_270 != 0);                                                   /* (neq _clm_270 0) */
  if ((!_clm_269)) goto L_267;
  _clm_273 = mus_env(SR_SPREAD_ENV);                                            /* (env SR-SPREAD-ENV) */
                                                                                /* (random _clm_273) */
  _clm_272 = mus_frandom((double)(_clm_273));
  _clm_275 = mus_env(SR_SPREAD_ENV);                                            /* (env SR-SPREAD-ENV) */
  _clm_274 = ((double)_clm_275 / (double)((2)));
                                                                                /* (/ _clm_275 2) */
                                                                                /* (- _clm_272 _clm_274) */
  _clm_271 = ((_clm_272) - (_clm_274));
  clm_int[_clm_266 + 0] = 2;
  clm_double[_clm_266_r+0] = _clm_271;                                          /* (setf _clm_266 _clm_271) */
  goto L_268;
L_267:
  clm_int[_clm_266 + 0] = 1;
  clm_int[_clm_266 + 0 + 1] = 0;                                                /* (setf _clm_266 0) */
L_268:
  _clm_264 = pow((double)(((clm_int[SRATE_BASE] == 2) ? clm_double[SRATE_BASE_r] : (double)(clm_int[SRATE_BASE + 1]))), (double)(((clm_int[_clm_266] == 2) ? clm_double[_clm_266_r] : (double)(clm_int[_clm_266 + 1])))); /* (expt SRATE-BASE _clm_266) */
                                                                                /* (* _clm_263 _clm_264) */
  _clm_262 = ((_clm_263) * (_clm_264));
  clm_int[_clm_258 + 0] = 2;
  clm_double[_clm_258_r+0] = _clm_262;                                          /* (setf _clm_258 _clm_262) */
  goto L_260;
L_259:
  _clm_277 = mus_env(SR_ENV);                                                   /* (env SR-ENV) */
                                                                                /* (if (/= (env sr-spread-env) 0) */
  _clm_283 = mus_env(SR_SPREAD_ENV);                                            /* (env SR-SPREAD-ENV) */
  _clm_282 = (_clm_283 != 0);                                                   /* (neq _clm_283 0) */
  if ((!_clm_282)) goto L_280;
  _clm_286 = mus_env(SR_SPREAD_ENV);                                            /* (env SR-SPREAD-ENV) */
                                                                                /* (random _clm_286) */
  _clm_285 = mus_frandom((double)(_clm_286));
  _clm_288 = mus_env(SR_SPREAD_ENV);                                            /* (env SR-SPREAD-ENV) */
  _clm_287 = ((double)_clm_288 / (double)((2)));
                                                                                /* (/ _clm_288 2) */
                                                                                /* (- _clm_285 _clm_287) */
  _clm_284 = ((_clm_285) - (_clm_287));
  clm_int[_clm_279 + 0] = 2;
  clm_double[_clm_279_r+0] = _clm_284;                                          /* (setf _clm_279 _clm_284) */
  goto L_281;
L_280:
  clm_int[_clm_279 + 0] = 1;
  clm_int[_clm_279 + 0 + 1] = 0;                                                /* (setf _clm_279 0) */
L_281:
                                                                                /* (+ _clm_277 _clm_279) */
  _clm_276 = ((_clm_277) + (((clm_int[_clm_279] == 2) ? clm_double[_clm_279_r] : (double)(clm_int[_clm_279 + 1]))));
  clm_int[_clm_258 + 0] = 2;
  clm_double[_clm_258_r+0] = _clm_276;                                          /* (setf _clm_258 _clm_276) */
L_260:
  clm_int[GR_SRATE + 0] = clm_int[_clm_258 + 0];
  clm_int[GR_SRATE + 0 + 1] = clm_int[_clm_258 + 0 + 1];
  clm_double[GR_SRATE_r + 0] = clm_double[_clm_258_r + 0];                      /* (setf GR-SRATE _clm_258) */
  mus_set_increment(IN_FILE_READER, ((clm_int[GR_SRATE] == 2) ? clm_double[GR_SRATE_r] : (double)(clm_int[GR_SRATE + 1])));
  _clm_290 = ((double)1 / (double)((((clm_int[SRATE_RATIO] == 2) ? clm_double[SRATE_RATIO_r] : (double)(clm_int[SRATE_RATIO + 1])))));
                                                                                /* (/ 1 srate-ratio) */
  _clm_289 = (mus_long_t)floor((double)(((clm_int[GR_SAMPLES] == 2) ? clm_double[GR_SAMPLES_r] : (double)(clm_int[GR_SAMPLES + 1]))) / (double)(_clm_290)); /* (floor GR-SAMPLES _clm_290) */
  clm_int[IN_SAMPLES + 0] = 1;
  clm_int[IN_SAMPLES + 0 + 1] = _clm_289;                                       /* (setf IN-SAMPLES _clm_289) */
  mus_set_phase(GR_ENV, 0.0);
  mus_set_phase(GR_ENV_END, 0.0);
  _clm_291 = ((double)1 / (double)((((clm_int[GR_DURATION] == 2) ? clm_double[GR_DURATION_r] : (double)(clm_int[GR_DURATION + 1])))));
                                                                                /* (/ 1 gr-duration) */
  mus_set_frequency(GR_ENV, _clm_291);
  _clm_292 = ((double)1 / (double)((((clm_int[GR_DURATION] == 2) ? clm_double[GR_DURATION_r] : (double)(clm_int[GR_DURATION + 1])))));
                                                                                /* (/ 1 gr-duration) */
  mus_set_frequency(GR_ENV_END, _clm_292);
  _clm_293 = mus_env(GR_DENS_ENV);                                              /* (env GR-DENS-ENV) */
  clm_int[GR_DENS + 0] = 2;
  clm_double[GR_DENS_r+0] = _clm_293;                                           /* (setf GR-DENS _clm_293) */
                                                                                /* (if (/= (env gr-dens-spread-env) 0) */
  _clm_299 = mus_env(GR_DENS_SPREAD_ENV);                                       /* (env GR-DENS-SPREAD-ENV) */
  _clm_298 = (_clm_299 != 0);                                                   /* (neq _clm_299 0) */
  if ((!_clm_298)) goto L_296;
  _clm_302 = mus_env(GR_DENS_SPREAD_ENV);                                       /* (env GR-DENS-SPREAD-ENV) */
                                                                                /* (random _clm_302) */
  _clm_301 = mus_frandom((double)(_clm_302));
  _clm_304 = mus_env(GR_DENS_SPREAD_ENV);                                       /* (env GR-DENS-SPREAD-ENV) */
  _clm_303 = ((double)_clm_304 / (double)((2)));
                                                                                /* (/ _clm_304 2) */
                                                                                /* (- _clm_301 _clm_303) */
  _clm_300 = ((_clm_301) - (_clm_303));
  clm_int[_clm_295 + 0] = 2;
  clm_double[_clm_295_r+0] = _clm_300;                                          /* (setf _clm_295 _clm_300) */
  goto L_297;
L_296:
  clm_int[_clm_295 + 0] = 1;
  clm_int[_clm_295 + 0 + 1] = 0;                                                /* (setf _clm_295 0) */
L_297:
  clm_int[GR_DENS_SPREAD + 0] = clm_int[_clm_295 + 0];
  clm_int[GR_DENS_SPREAD + 0 + 1] = clm_int[_clm_295 + 0 + 1];
  clm_double[GR_DENS_SPREAD_r + 0] = clm_double[_clm_295_r + 0];                /* (setf GR-DENS-SPREAD _clm_295) */
                                                                                /* (+ samples gr-samples) */
  if ((clm_int[SAMPLES + 0] == 1) && (clm_int[GR_SAMPLES + 0] == 1))
    {clm_int[_clm_305 + 0] = 1;
  clm_int[_clm_305 + 0 + 1] = ((clm_int[SAMPLES + 0 + 1]) + (clm_int[GR_SAMPLES + 0 + 1]));}
  else {clm_int[_clm_305 + 0] = 2;
  clm_double[_clm_305_r+0] = ((((clm_int[SAMPLES] == 2) ? clm_double[SAMPLES_r] : (double)(clm_int[SAMPLES + 1]))) + (((clm_int[GR_SAMPLES] == 2) ? clm_double[GR_SAMPLES_r] : (double)(clm_int[GR_SAMPLES + 1]))));}
  clm_int[SAMPLES + 0] = clm_int[_clm_305 + 0];
  clm_int[SAMPLES + 0 + 1] = clm_int[_clm_305 + 0 + 1];
  clm_double[SAMPLES_r + 0] = clm_double[_clm_305_r + 0];                       /* (setf SAMPLES _clm_305) */
                                                                                /* (+ grain-counter 1) */
  if ((clm_int[GRAIN_COUNTER + 0] == 1) && (1))
    {clm_int[_clm_306 + 0] = 1;
  clm_int[_clm_306 + 0 + 1] = ((clm_int[GRAIN_COUNTER + 0 + 1]) + (1));}
  else {clm_int[_clm_306 + 0] = 2;
  clm_double[_clm_306_r+0] = ((((clm_int[GRAIN_COUNTER] == 2) ? clm_double[GRAIN_COUNTER_r] : (double)(clm_int[GRAIN_COUNTER + 1]))) + (1));}
  clm_int[GRAIN_COUNTER + 0] = clm_int[_clm_306 + 0];
  clm_int[GRAIN_COUNTER + 0 + 1] = clm_int[_clm_306 + 0 + 1];
  clm_double[GRAIN_COUNTER_r + 0] = clm_double[_clm_306_r + 0];                 /* (setf GRAIN-COUNTER _clm_306) */
                                                                                /* (cond */
  _clm_311 = (((clm_int[WHERE_TO] == 2) ? clm_double[WHERE_TO_r] : (double)(clm_int[WHERE_TO + 1])) == 1); /* (== WHERE-TO 1) */
  clm_int[_clm_308 + 0] = 0;
  clm_int[_clm_308 + 0 + 1] = _clm_311;                                         /* (setf _clm_308 _clm_311) */
  if ((!_clm_311)) goto L_310;
  clm_int[_clm_308 + 0] = clm_int[GR_DURATION + 0];
  clm_int[_clm_308 + 0 + 1] = clm_int[GR_DURATION + 0 + 1];
  clm_double[_clm_308_r + 0] = clm_double[GR_DURATION_r + 0];                   /* (setf _clm_308 GR-DURATION) */
  goto L_309;
L_310:
  _clm_313 = (((clm_int[WHERE_TO] == 2) ? clm_double[WHERE_TO_r] : (double)(clm_int[WHERE_TO + 1])) == 2); /* (== WHERE-TO 2) */
  clm_int[_clm_308 + 0] = 0;
  clm_int[_clm_308 + 0 + 1] = _clm_313;                                         /* (setf _clm_308 _clm_313) */
  if ((!_clm_313)) goto L_312;
  clm_int[_clm_308 + 0] = clm_int[IN_START_VALUE + 0];
  clm_int[_clm_308 + 0 + 1] = clm_int[IN_START_VALUE + 0 + 1];
  clm_double[_clm_308_r + 0] = clm_double[IN_START_VALUE_r + 0];                /* (setf _clm_308 IN-START-VALUE) */
  goto L_309;
L_312:
  _clm_315 = (((clm_int[WHERE_TO] == 2) ? clm_double[WHERE_TO_r] : (double)(clm_int[WHERE_TO + 1])) == 3); /* (== WHERE-TO 3) */
  clm_int[_clm_308 + 0] = 0;
  clm_int[_clm_308 + 0 + 1] = _clm_315;                                         /* (setf _clm_308 _clm_315) */
  if ((!_clm_315)) goto L_314;
  clm_int[_clm_308 + 0] = clm_int[GR_SRATE + 0];
  clm_int[_clm_308 + 0 + 1] = clm_int[GR_SRATE + 0 + 1];
  clm_double[_clm_308_r + 0] = clm_double[GR_SRATE_r + 0];                      /* (setf _clm_308 GR-SRATE) */
  goto L_309;
L_314:
  _clm_317 = (((clm_int[WHERE_TO] == 2) ? clm_double[WHERE_TO_r] : (double)(clm_int[WHERE_TO + 1])) == 4); /* (== WHERE-TO 4) */
  clm_int[_clm_308 + 0] = 0;
  clm_int[_clm_308 + 0 + 1] = _clm_317;                                         /* (setf _clm_308 _clm_317) */
  if ((!_clm_317)) goto L_316;
                                                                                /* (random 1.0) */
  _clm_318 = mus_frandom((double)(1.0));
  clm_int[_clm_308 + 0] = 2;
  clm_double[_clm_308_r+0] = _clm_318;                                          /* (setf _clm_308 _clm_318) */
  goto L_309;
L_316:
  clm_int[_clm_308 + 0] = 0;
  clm_int[_clm_308 + 0 + 1] = 0;                                                /* (setf _clm_308 NIL) */
L_309:
  clm_int[WHERE + 0] = clm_int[_clm_308 + 0];
  clm_int[WHERE + 0 + 1] = clm_int[_clm_308 + 0 + 1];
  clm_double[WHERE_r + 0] = clm_double[_clm_308_r + 0];                         /* (setf WHERE _clm_308) */
                                                                                /* (if where */
  if (((clm_int[WHERE] == 0) && (clm_int[WHERE + 1] == 0))) goto L_320;
  C = 0;                                                                        /* (setf C 0) */
  _clm_328 = ((clm_int[BINS + 0] == 38) ? clm_int[clm_int[BINS + 0 + 1] + 1] : CLM_ARR_SIZE(clm_int[BINS + 0 + 1])); /* (length BINS) */
                                                                                /* (- _clm_328 1) */
  _clm_327 = ((_clm_328) - (1));
  LOOP_LIMIT_323 = _clm_327;                                                    /* (setf LOOP-LIMIT-323 _clm_327) */
                                                                                /* (tagbody */
NEXT_LOOP_L_28:
                                                                                /* (if (>= c loop-limit-323) */
  _clm_336 = (C >= LOOP_LIMIT_323);                                             /* (>= C LOOP-LIMIT-323) */
  if ((!_clm_336)) goto L_334;
                                                                                /* (progn */
                                                                                /* (go end-loop */
  goto END_LOOP_L_28;
  goto L_335;
L_334:
L_335:
                                                                                /* (if (< (aref bins c) where (aref bins (+ c 1))) */
  {int lci; lci = C;
  switch (CLM_ARR_TYPE(clm_int[BINS + 0 + 1]))
    {
    case 36: clm_int[_clm_344 + 0] = 2;
  clm_double[_clm_344_r+0] = clm_double[CLM_ARR_RBLOCK(clm_int[BINS + 0 + 1]) + lci]; break;
    case 37: clm_int[_clm_344 + 0] = 1;
  clm_int[_clm_344 + 0 + 1] = clm_int[CLM_ARR_IBLOCK(clm_int[BINS + 0 + 1]) + lci]; break;
    default: {
      int iblock, rblock;
      iblock = CLM_ARR_IBLOCK(clm_int[BINS + 0 + 1]) + (lci * 2); rblock = CLM_ARR_RBLOCK(clm_int[BINS + 0 + 1]) + lci;
      clm_int[_clm_344 + 0] = clm_int[iblock];
      clm_int[_clm_344 + 0 + 1] = clm_int[iblock+1];
      clm_double[_clm_344_r + 0] = clm_double[rblock];
  }}}

                                                                                /* (+ c 1) */
  _clm_346 = ((C) + (1));
  {int lci; lci = _clm_346;
  switch (CLM_ARR_TYPE(clm_int[BINS + 0 + 1]))
    {
    case 36: clm_int[_clm_345 + 0] = 2;
  clm_double[_clm_345_r+0] = clm_double[CLM_ARR_RBLOCK(clm_int[BINS + 0 + 1]) + lci]; break;
    case 37: clm_int[_clm_345 + 0] = 1;
  clm_int[_clm_345 + 0 + 1] = clm_int[CLM_ARR_IBLOCK(clm_int[BINS + 0 + 1]) + lci]; break;
    default: {
      int iblock, rblock;
      iblock = CLM_ARR_IBLOCK(clm_int[BINS + 0 + 1]) + (lci * 2); rblock = CLM_ARR_RBLOCK(clm_int[BINS + 0 + 1]) + lci;
      clm_int[_clm_345 + 0] = clm_int[iblock];
      clm_int[_clm_345 + 0 + 1] = clm_int[iblock+1];
      clm_double[_clm_345_r + 0] = clm_double[rblock];
  }}}

  _clm_343 = ((((clm_int[_clm_344] == 2) ? clm_double[_clm_344_r] : (double)(clm_int[_clm_344 + 1])) < ((clm_int[WHERE] == 2) ? clm_double[WHERE_r] : (double)(clm_int[WHERE + 1]))) && (((clm_int[WHERE] == 2) ? clm_double[WHERE_r] : (double)(clm_int[WHERE + 1])) < ((clm_int[_clm_345] == 2) ? clm_double[_clm_345_r] : (double)(clm_int[_clm_345 + 1])))); /* (< _clm_344 WHERE _clm_345) */
  if ((!_clm_343)) goto L_341;
  clm_int[_clm_340 + 0] = 2;
  clm_double[_clm_340_r+0] = 1.0;                                               /* (setf _clm_340 1.0) */
  goto L_342;
L_341:
  clm_int[_clm_340 + 0] = 2;
  clm_double[_clm_340_r+0] = 0.0;                                               /* (setf _clm_340 0.0) */
L_342:
  mus_locsig_set(LOC, C, ((clm_int[_clm_340] == 2) ? clm_double[_clm_340_r] : (double)(clm_int[_clm_340 + 1])));
  _clm_348 = C + 1.0;
  C = _clm_348;                                                                 /* (setf C _clm_348) */
                                                                                /* (go next-loop */
  goto NEXT_LOOP_L_28;
END_LOOP_L_28:
                                                                                /* (block nil */
  goto L_321;
L_320:
                                                                                /* (if (= where-to grani-to-grain-allchans) */
  _clm_353 = (((clm_int[WHERE_TO] == 2) ? clm_double[WHERE_TO_r] : (double)(clm_int[WHERE_TO + 1])) == 5); /* (== WHERE-TO 5) */
  if ((!_clm_353)) goto L_351;
  C = 0;                                                                        /* (setf C 0) */
  _clm_359 = mus_channels(_OUTPUT_);
  LOOP_LIMIT_355 = _clm_359;                                                    /* (setf LOOP-LIMIT-355 _clm_359) */
                                                                                /* (tagbody */
NEXT_LOOP_L_29:
                                                                                /* (if (>= c loop-limit-355) */
  _clm_367 = (C >= LOOP_LIMIT_355);                                             /* (>= C LOOP-LIMIT-355) */
  if ((!_clm_367)) goto L_365;
                                                                                /* (progn */
                                                                                /* (go end-loop */
  goto END_LOOP_L_29;
  goto L_366;
L_365:
L_366:
  mus_locsig_set(LOC, C, 1.0);
  _clm_372 = C + 1.0;
  C = _clm_372;                                                                 /* (setf C _clm_372) */
                                                                                /* (go next-loop */
  goto NEXT_LOOP_L_29;
END_LOOP_L_29:
                                                                                /* (block nil */
  goto L_352;
L_351:
                                                                                /* (progn */
  mus_set_location(GR_DIST, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_DIST_SPREAD, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_DEGREE, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  mus_set_location(GR_DEGREE_SPREAD, ((clm_int[GR_FROM_BEG] == 2) ? clm_double[GR_FROM_BEG_r] : (double)(clm_int[GR_FROM_BEG + 1])));
  _clm_377 = mus_env(GR_DEGREE);                                                /* (env GR-DEGREE) */
                                                                                /* (if (/= (env gr-degree-spread) 0) */
  _clm_383 = mus_env(GR_DEGREE_SPREAD);                                         /* (env GR-DEGREE-SPREAD) */
  _clm_382 = (_clm_383 != 0);                                                   /* (neq _clm_383 0) */
  if ((!_clm_382)) goto L_380;
  _clm_386 = mus_env(GR_DEGREE_SPREAD);                                         /* (env GR-DEGREE-SPREAD) */
                                                                                /* (random _clm_386) */
  _clm_385 = mus_frandom((double)(_clm_386));
  _clm_388 = mus_env(GR_DEGREE_SPREAD);                                         /* (env GR-DEGREE-SPREAD) */
  _clm_387 = ((double)_clm_388 / (double)((2)));
                                                                                /* (/ _clm_388 2) */
                                                                                /* (- _clm_385 _clm_387) */
  _clm_384 = ((_clm_385) - (_clm_387));
  clm_int[_clm_379 + 0] = 2;
  clm_double[_clm_379_r+0] = _clm_384;                                          /* (setf _clm_379 _clm_384) */
  goto L_381;
L_380:
  clm_int[_clm_379 + 0] = 1;
  clm_int[_clm_379 + 0 + 1] = 0;                                                /* (setf _clm_379 0) */
L_381:
                                                                                /* (+ _clm_377 _clm_379) */
  _clm_376 = ((_clm_377) + (((clm_int[_clm_379] == 2) ? clm_double[_clm_379_r] : (double)(clm_int[_clm_379 + 1]))));
  clm_int[DEG + 0] = 2;
  clm_double[DEG_r+0] = _clm_376;                                               /* (setf DEG _clm_376) */
  _clm_390 = mus_env(GR_DIST);                                                  /* (env GR-DIST) */
                                                                                /* (if (/= (env gr-dist-spread) 0) */
  _clm_396 = mus_env(GR_DIST_SPREAD);                                           /* (env GR-DIST-SPREAD) */
  _clm_395 = (_clm_396 != 0);                                                   /* (neq _clm_396 0) */
  if ((!_clm_395)) goto L_393;
  _clm_399 = mus_env(GR_DIST_SPREAD);                                           /* (env GR-DIST-SPREAD) */
                                                                                /* (random _clm_399) */
  _clm_398 = mus_frandom((double)(_clm_399));
  _clm_401 = mus_env(GR_DIST_SPREAD);                                           /* (env GR-DIST-SPREAD) */
  _clm_400 = ((double)_clm_401 / (double)((2)));
                                                                                /* (/ _clm_401 2) */
                                                                                /* (- _clm_398 _clm_400) */
  _clm_397 = ((_clm_398) - (_clm_400));
  clm_int[_clm_392 + 0] = 2;
  clm_double[_clm_392_r+0] = _clm_397;                                          /* (setf _clm_392 _clm_397) */
  goto L_394;
L_393:
  clm_int[_clm_392 + 0] = 1;
  clm_int[_clm_392 + 0 + 1] = 0;                                                /* (setf _clm_392 0) */
L_394:
                                                                                /* (+ _clm_390 _clm_392) */
  _clm_389 = ((_clm_390) + (((clm_int[_clm_392] == 2) ? clm_double[_clm_392_r] : (double)(clm_int[_clm_392 + 1]))));
  clm_int[DIST + 0] = 2;
  clm_double[DIST_r+0] = _clm_389;                                              /* (setf DIST _clm_389) */
  _clm_403 = ((((clm_int[DIST] == 2) ? clm_double[DIST_r] : (double)(clm_int[DIST + 1])) > 1.0) ? ((clm_int[DIST] == 2) ? clm_double[DIST_r] : (double)(clm_int[DIST + 1])) : 1.0); /* (max DIST 1.0) */
  _clm_402 = ((double)1.0 / (double)((_clm_403)));
                                                                                /* (/ 1.0 _clm_403) */
  clm_int[DIST_SCL + 0] = 2;
  clm_double[DIST_SCL_r+0] = _clm_402;                                          /* (setf DIST-SCL _clm_402) */
  _clm_406 = ((((clm_int[DIST] == 2) ? clm_double[DIST_r] : (double)(clm_int[DIST + 1])) > 1.0) ? ((clm_int[DIST] == 2) ? clm_double[DIST_r] : (double)(clm_int[DIST + 1])) : 1.0); /* (max DIST 1.0) */
  _clm_405 = sqrt((double)(_clm_406));                                          /* (sqrt _clm_406) */
  _clm_404 = ((double)1.0 / (double)((_clm_405)));
                                                                                /* (/ 1.0 _clm_405) */
  clm_int[DIST_RSCL + 0] = 2;
  clm_double[DIST_RSCL_r+0] = _clm_404;                                         /* (setf DIST-RSCL _clm_404) */
                                                                                /* (if *reverb* */
  if (((clm_int[_REVERB_] == 0) && (clm_int[_REVERB_ + 1] == 0))) goto L_408;
                                                                                /* (* reverb-amount dist-rscl) */
  if ((clm_int[REVERB_AMOUNT + 0] == 1) && (clm_int[DIST_RSCL + 0] == 1))
    {clm_int[_clm_411 + 0] = 1;
  clm_int[_clm_411 + 0 + 1] = ((clm_int[REVERB_AMOUNT + 0 + 1]) * (clm_int[DIST_RSCL + 0 + 1]));}
  else {clm_int[_clm_411 + 0] = 2;
  clm_double[_clm_411_r+0] = ((((clm_int[REVERB_AMOUNT] == 2) ? clm_double[REVERB_AMOUNT_r] : (double)(clm_int[REVERB_AMOUNT + 1]))) * (((clm_int[DIST_RSCL] == 2) ? clm_double[DIST_RSCL_r] : (double)(clm_int[DIST_RSCL + 1]))));}
  mus_locsig_reverb_set(LOC, 0, ((clm_int[_clm_411] == 2) ? clm_double[_clm_411_r] : (double)(clm_int[_clm_411 + 1])));
  goto L_409;
L_408:
L_409:
                                                                                /* (if (= out-chans 1) */
  _clm_415 = (((clm_int[OUT_CHANS] == 2) ? clm_double[OUT_CHANS_r] : (double)(clm_int[OUT_CHANS + 1])) == 1); /* (== OUT-CHANS 1) */
  if ((!_clm_415)) goto L_413;
  mus_locsig_set(LOC, 0, ((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1])));
  goto L_414;
L_413:
                                                                                /* (if (= out-chans 2) */
  _clm_420 = (((clm_int[OUT_CHANS] == 2) ? clm_double[OUT_CHANS_r] : (double)(clm_int[OUT_CHANS + 1])) == 2); /* (== OUT-CHANS 2) */
  if ((!_clm_420)) goto L_418;
  _clm_424 = ((0.0 > ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) ? 0.0 : ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))); /* (max 0.0 DEG) */
  _clm_423 = ((90.0 < _clm_424) ? 90.0 : _clm_424);                             /* (min 90.0 _clm_424) */
  _clm_422 = ((double)_clm_423 / (double)((90.0)));
                                                                                /* (/ _clm_423 90.0) */
  FRAC = _clm_422;                                                              /* (setf FRAC _clm_422) */
                                                                                /* (- 1.0 frac) */
  _clm_427 = ((1.0) - (FRAC));
                                                                                /* (* dist-scl _clm_427) */
  _clm_426 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_427));
  mus_locsig_set(LOC, 0, _clm_426);
                                                                                /* (* dist-scl frac) */
  _clm_428 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (FRAC));
  mus_locsig_set(LOC, 1, _clm_428);
  goto L_419;
L_418:
                                                                                /* (if (> out-chans 2) */
  _clm_432 = (((clm_int[OUT_CHANS] == 2) ? clm_double[OUT_CHANS_r] : (double)(clm_int[OUT_CHANS + 1])) > 2); /* (> OUT-CHANS 2) */
  if ((!_clm_432)) goto L_430;
                                                                                /* (progn */
                                                                                /* (if (<= 0 deg 90) */
  _clm_438 = ((0 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 90)); /* (<= 0 DEG 90) */
  if ((!_clm_438)) goto L_436;
                                                                                /* (- 90 deg) */
  if ((1) && (clm_int[DEG + 0] == 1))
    {clm_int[_clm_441 + 0] = 1;
  clm_int[_clm_441 + 0 + 1] = ((90) - (clm_int[DEG + 0 + 1]));}
  else {clm_int[_clm_441 + 0] = 2;
  clm_double[_clm_441_r+0] = ((90) - (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))));}
  _clm_440 = ((double)((clm_int[_clm_441] == 2) ? clm_double[_clm_441_r] : (double)(clm_int[_clm_441 + 1])) / (double)((90.0)));
                                                                                /* (/ _clm_441 90.0) */
                                                                                /* (* dist-scl _clm_440) */
  _clm_439 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_440));
  clm_int[_clm_435 + 0] = 2;
  clm_double[_clm_435_r+0] = _clm_439;                                          /* (setf _clm_435 _clm_439) */
  goto L_437;
L_436:
                                                                                /* (if (<= 270 deg 360) */
  _clm_445 = ((270 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 360)); /* (<= 270 DEG 360) */
  if ((!_clm_445)) goto L_443;
                                                                                /* (- deg 270) */
  if ((clm_int[DEG + 0] == 1) && (1))
    {clm_int[_clm_448 + 0] = 1;
  clm_int[_clm_448 + 0 + 1] = ((clm_int[DEG + 0 + 1]) - (270));}
  else {clm_int[_clm_448 + 0] = 2;
  clm_double[_clm_448_r+0] = ((((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) - (270));}
  _clm_447 = ((double)((clm_int[_clm_448] == 2) ? clm_double[_clm_448_r] : (double)(clm_int[_clm_448 + 1])) / (double)((90)));
                                                                                /* (/ _clm_448 90) */
                                                                                /* (* dist-scl _clm_447) */
  _clm_446 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_447));
  clm_int[_clm_442 + 0] = 2;
  clm_double[_clm_442_r+0] = _clm_446;                                          /* (setf _clm_442 _clm_446) */
  goto L_444;
L_443:
  clm_int[_clm_442 + 0] = 2;
  clm_double[_clm_442_r+0] = 0.0;                                               /* (setf _clm_442 0.0) */
L_444:
  clm_int[_clm_435 + 0] = clm_int[_clm_442 + 0];
  clm_int[_clm_435 + 0 + 1] = clm_int[_clm_442 + 0 + 1];
  clm_double[_clm_435_r + 0] = clm_double[_clm_442_r + 0];                      /* (setf _clm_435 _clm_442) */
L_437:
  mus_locsig_set(LOC, 0, ((clm_int[_clm_435] == 2) ? clm_double[_clm_435_r] : (double)(clm_int[_clm_435 + 1])));
                                                                                /* (if (<= 90 deg 180) */
  _clm_452 = ((90 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 180)); /* (<= 90 DEG 180) */
  if ((!_clm_452)) goto L_450;
                                                                                /* (- 180 deg) */
  if ((1) && (clm_int[DEG + 0] == 1))
    {clm_int[_clm_455 + 0] = 1;
  clm_int[_clm_455 + 0 + 1] = ((180) - (clm_int[DEG + 0 + 1]));}
  else {clm_int[_clm_455 + 0] = 2;
  clm_double[_clm_455_r+0] = ((180) - (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))));}
  _clm_454 = ((double)((clm_int[_clm_455] == 2) ? clm_double[_clm_455_r] : (double)(clm_int[_clm_455 + 1])) / (double)((90.0)));
                                                                                /* (/ _clm_455 90.0) */
                                                                                /* (* dist-scl _clm_454) */
  _clm_453 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_454));
  clm_int[_clm_449 + 0] = 2;
  clm_double[_clm_449_r+0] = _clm_453;                                          /* (setf _clm_449 _clm_453) */
  goto L_451;
L_450:
                                                                                /* (if (<= 0 deg 90) */
  _clm_459 = ((0 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 90)); /* (<= 0 DEG 90) */
  if ((!_clm_459)) goto L_457;
  _clm_461 = ((double)((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) / (double)((90)));
                                                                                /* (/ DEG 90) */
                                                                                /* (* dist-scl _clm_461) */
  _clm_460 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_461));
  clm_int[_clm_456 + 0] = 2;
  clm_double[_clm_456_r+0] = _clm_460;                                          /* (setf _clm_456 _clm_460) */
  goto L_458;
L_457:
  clm_int[_clm_456 + 0] = 2;
  clm_double[_clm_456_r+0] = 0.0;                                               /* (setf _clm_456 0.0) */
L_458:
  clm_int[_clm_449 + 0] = clm_int[_clm_456 + 0];
  clm_int[_clm_449 + 0 + 1] = clm_int[_clm_456 + 0 + 1];
  clm_double[_clm_449_r + 0] = clm_double[_clm_456_r + 0];                      /* (setf _clm_449 _clm_456) */
L_451:
  mus_locsig_set(LOC, 1, ((clm_int[_clm_449] == 2) ? clm_double[_clm_449_r] : (double)(clm_int[_clm_449 + 1])));
                                                                                /* (if (<= 180 deg 270) */
  _clm_465 = ((180 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 270)); /* (<= 180 DEG 270) */
  if ((!_clm_465)) goto L_463;
                                                                                /* (- 270 deg) */
  if ((1) && (clm_int[DEG + 0] == 1))
    {clm_int[_clm_468 + 0] = 1;
  clm_int[_clm_468 + 0 + 1] = ((270) - (clm_int[DEG + 0 + 1]));}
  else {clm_int[_clm_468 + 0] = 2;
  clm_double[_clm_468_r+0] = ((270) - (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))));}
  _clm_467 = ((double)((clm_int[_clm_468] == 2) ? clm_double[_clm_468_r] : (double)(clm_int[_clm_468 + 1])) / (double)((90.0)));
                                                                                /* (/ _clm_468 90.0) */
                                                                                /* (* dist-scl _clm_467) */
  _clm_466 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_467));
  clm_int[_clm_462 + 0] = 2;
  clm_double[_clm_462_r+0] = _clm_466;                                          /* (setf _clm_462 _clm_466) */
  goto L_464;
L_463:
                                                                                /* (if (<= 90 deg 180) */
  _clm_472 = ((90 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 180)); /* (<= 90 DEG 180) */
  if ((!_clm_472)) goto L_470;
                                                                                /* (- deg 90) */
  if ((clm_int[DEG + 0] == 1) && (1))
    {clm_int[_clm_475 + 0] = 1;
  clm_int[_clm_475 + 0 + 1] = ((clm_int[DEG + 0 + 1]) - (90));}
  else {clm_int[_clm_475 + 0] = 2;
  clm_double[_clm_475_r+0] = ((((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) - (90));}
  _clm_474 = ((double)((clm_int[_clm_475] == 2) ? clm_double[_clm_475_r] : (double)(clm_int[_clm_475 + 1])) / (double)((90)));
                                                                                /* (/ _clm_475 90) */
                                                                                /* (* dist-scl _clm_474) */
  _clm_473 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_474));
  clm_int[_clm_469 + 0] = 2;
  clm_double[_clm_469_r+0] = _clm_473;                                          /* (setf _clm_469 _clm_473) */
  goto L_471;
L_470:
  clm_int[_clm_469 + 0] = 2;
  clm_double[_clm_469_r+0] = 0.0;                                               /* (setf _clm_469 0.0) */
L_471:
  clm_int[_clm_462 + 0] = clm_int[_clm_469 + 0];
  clm_int[_clm_462 + 0 + 1] = clm_int[_clm_469 + 0 + 1];
  clm_double[_clm_462_r + 0] = clm_double[_clm_469_r + 0];                      /* (setf _clm_462 _clm_469) */
L_464:
  mus_locsig_set(LOC, 2, ((clm_int[_clm_462] == 2) ? clm_double[_clm_462_r] : (double)(clm_int[_clm_462 + 1])));
                                                                                /* (if (> out-chans 3) */
  _clm_479 = (((clm_int[OUT_CHANS] == 2) ? clm_double[OUT_CHANS_r] : (double)(clm_int[OUT_CHANS + 1])) > 3); /* (> OUT-CHANS 3) */
  if ((!_clm_479)) goto L_477;
                                                                                /* (if (<= 270 deg 360) */
  _clm_484 = ((270 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 360)); /* (<= 270 DEG 360) */
  if ((!_clm_484)) goto L_482;
                                                                                /* (- 360 deg) */
  if ((1) && (clm_int[DEG + 0] == 1))
    {clm_int[_clm_487 + 0] = 1;
  clm_int[_clm_487 + 0 + 1] = ((360) - (clm_int[DEG + 0 + 1]));}
  else {clm_int[_clm_487 + 0] = 2;
  clm_double[_clm_487_r+0] = ((360) - (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))));}
  _clm_486 = ((double)((clm_int[_clm_487] == 2) ? clm_double[_clm_487_r] : (double)(clm_int[_clm_487 + 1])) / (double)((90.0)));
                                                                                /* (/ _clm_487 90.0) */
                                                                                /* (* dist-scl _clm_486) */
  _clm_485 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_486));
  clm_int[_clm_481 + 0] = 2;
  clm_double[_clm_481_r+0] = _clm_485;                                          /* (setf _clm_481 _clm_485) */
  goto L_483;
L_482:
                                                                                /* (if (<= 180 deg 270) */
  _clm_491 = ((180 <= ((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) && (((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1])) <= 270)); /* (<= 180 DEG 270) */
  if ((!_clm_491)) goto L_489;
                                                                                /* (- deg 180) */
  if ((clm_int[DEG + 0] == 1) && (1))
    {clm_int[_clm_494 + 0] = 1;
  clm_int[_clm_494 + 0 + 1] = ((clm_int[DEG + 0 + 1]) - (180));}
  else {clm_int[_clm_494 + 0] = 2;
  clm_double[_clm_494_r+0] = ((((clm_int[DEG] == 2) ? clm_double[DEG_r] : (double)(clm_int[DEG + 1]))) - (180));}
  _clm_493 = ((double)((clm_int[_clm_494] == 2) ? clm_double[_clm_494_r] : (double)(clm_int[_clm_494 + 1])) / (double)((90)));
                                                                                /* (/ _clm_494 90) */
                                                                                /* (* dist-scl _clm_493) */
  _clm_492 = ((((clm_int[DIST_SCL] == 2) ? clm_double[DIST_SCL_r] : (double)(clm_int[DIST_SCL + 1]))) * (_clm_493));
  clm_int[_clm_488 + 0] = 2;
  clm_double[_clm_488_r+0] = _clm_492;                                          /* (setf _clm_488 _clm_492) */
  goto L_490;
L_489:
  clm_int[_clm_488 + 0] = 2;
  clm_double[_clm_488_r+0] = 0.0;                                               /* (setf _clm_488 0.0) */
L_490:
  clm_int[_clm_481 + 0] = clm_int[_clm_488 + 0];
  clm_int[_clm_481 + 0 + 1] = clm_int[_clm_488 + 0 + 1];
  clm_double[_clm_481_r + 0] = clm_double[_clm_488_r + 0];                      /* (setf _clm_481 _clm_488) */
L_483:
  mus_locsig_set(LOC, 3, ((clm_int[_clm_481] == 2) ? clm_double[_clm_481_r] : (double)(clm_int[_clm_481 + 1])));
  goto L_478;
L_477:
L_478:
  goto L_431;
L_430:
L_431:
L_419:
L_414:
L_352:
L_321:
                                                                                /* (if (> (+ in-start in-samples) last-in-sample) */
                                                                                /* (+ in-start in-samples) */
  if ((clm_int[IN_START + 0] == 1) && (clm_int[IN_SAMPLES + 0] == 1))
    {clm_int[_clm_499 + 0] = 1;
  clm_int[_clm_499 + 0 + 1] = ((clm_int[IN_START + 0 + 1]) + (clm_int[IN_SAMPLES + 0 + 1]));}
  else {clm_int[_clm_499 + 0] = 2;
  clm_double[_clm_499_r+0] = ((((clm_int[IN_START] == 2) ? clm_double[IN_START_r] : (double)(clm_int[IN_START + 1]))) + (((clm_int[IN_SAMPLES] == 2) ? clm_double[IN_SAMPLES_r] : (double)(clm_int[IN_SAMPLES + 1]))));}
  _clm_498 = (((clm_int[_clm_499] == 2) ? clm_double[_clm_499_r] : (double)(clm_int[_clm_499 + 1])) > ((clm_int[LAST_IN_SAMPLE] == 2) ? clm_double[LAST_IN_SAMPLE_r] : (double)(clm_int[LAST_IN_SAMPLE + 1]))); /* (> _clm_499 LAST-IN-SAMPLE) */
  if ((!_clm_498)) goto L_496;
                                                                                /* (- last-in-sample in-samples) */
  if ((clm_int[LAST_IN_SAMPLE + 0] == 1) && (clm_int[IN_SAMPLES + 0] == 1))
    {clm_int[_clm_501 + 0] = 1;
  clm_int[_clm_501 + 0 + 1] = ((clm_int[LAST_IN_SAMPLE + 0 + 1]) - (clm_int[IN_SAMPLES + 0 + 1]));}
  else {clm_int[_clm_501 + 0] = 2;
  clm_double[_clm_501_r+0] = ((((clm_int[LAST_IN_SAMPLE] == 2) ? clm_double[LAST_IN_SAMPLE_r] : (double)(clm_int[LAST_IN_SAMPLE + 1]))) - (((clm_int[IN_SAMPLES] == 2) ? clm_double[IN_SAMPLES_r] : (double)(clm_int[IN_SAMPLES + 1]))));}
  clm_int[IN_START + 0] = clm_int[_clm_501 + 0];
  clm_int[IN_START + 0 + 1] = clm_int[_clm_501 + 0 + 1];
  clm_double[IN_START_r + 0] = clm_double[_clm_501_r + 0];                      /* (setf IN-START _clm_501) */
  goto L_497;
L_496:
                                                                                /* (if (< in-start 0) */
  _clm_505 = (((clm_int[IN_START] == 2) ? clm_double[IN_START_r] : (double)(clm_int[IN_START + 1])) < 0); /* (< IN-START 0) */
  if ((!_clm_505)) goto L_503;
  clm_int[IN_START + 0] = 1;
  clm_int[IN_START + 0 + 1] = 0;                                                /* (setf IN-START 0) */
  goto L_504;
L_503:
L_504:
L_497:
  mus_set_location(IN_FILE_READER, ((clm_int[IN_START] == 2) ? clm_double[IN_START_r] : (double)(clm_int[IN_START + 1])));
L_154:
                                                                                /* (go next-loop */
  goto NEXT_LOOP_L_27;
END_LOOP_L_27:
                                                                                /* (block nil */
goto RUN_ALL_DONE;

RUN_ALL_DONE:
  clm_signal(SIGINT,old_SIGINT);
  if (all_gens) clm_free_genbag(all_gens);

  return(1);
}

